# todo #https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3-requirements/Dockerfile

FROM python:3.12-slim

WORKDIR /app

# Copy requirements first for better caching
COPY requirements-controller.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY logger.py controller.py ./

# Command to run the application
CMD ["python", "-u", "controller.py"]