#https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3-requirements/Dockerfile

apiVersion: v1
kind: Pod
metadata:
  name: fixer
  namespace: gke-static-node-ip
  labels:
    app: gke-static-node-ip
    component: fixer
spec:
  serviceAccountName: gke-static-node-ip
  containers:
  - name: fixer
    image: gcr.io/callmyapp/gke-static-node-ip:fixer
    imagePullPolicy: Always
    env:
    - name: PROJECT_ID
      valueFrom:
        configMapKeyRef:
          name: fixer-config
          key: project_id
    - name: NETWORK_TIER
      valueFrom:
        configMapKeyRef:
          name: fixer-config
          key: network_tier
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: fixer-config
          key: log_level
---
apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: gke-static-node-ip
  labels:
    app: gke-static-node-ip
    component: controller
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: test2
  containers:
  - name: controller
    image: gcr.io/callmyapp/gke-static-node-ip:controller
    imagePullPolicy: Always
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NODES_DATA
      valueFrom:
        configMapKeyRef:
          name: controller-config
          key: dynamic_json_nodes_data
    - name: CHECK_RATE_SECONDS
      valueFrom:
        configMapKeyRef:
          name: controller-config
          key: check_rate_seconds
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: controller-config
          key: log_level