apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gke-static-node-ip@callmyapp-dev.iam.gserviceaccount.com
  name: gke-static-node-ip
  namespace: gke-static-node-ip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: distributor
  namespace: gke-static-node-ip
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gke-static-node-ip-distributor
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["controller-config"]
  verbs: ["get","patch","update"]
# - apiGroups: [""]
#   resources: ["pods/exec"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/log"]
#   verbs: ["get","list","watch"]
# - apiGroups: [""]
#   resources: ["events"]
#   verbs: ["watch"]
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: distributor
  namespace: default
subjects:
- kind: ServiceAccount
  name: distributor
  namespace: gke-static-node-ip
roleRef:
  kind: Role
  name: gke-static-node-ip-distributor
  apiGroup: rbac.authorization.k8s.io