apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: gke-static-node-ip
  labels:
    app: gke-static-node-ip
    component: controller
data:
  dynamic_json_nodes_data: ""
  check_rate_seconds: "15"
  log_level: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fixer-config
  namespace: gke-static-node-ip
  labels:
    app: gke-static-node-ip
    component: fixer
data:
  project_id: {{ .Values.projectId }}
  network_tier: {{ .Values.networkTier }}
  log_level: info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: distributor-config
  namespace: gke-static-node-ip
  labels:
    app: gke-static-node-ip
    component: distributor
data:
  nodepools_desired_ips: |
    {{ .Values.nodesDesiredIps | toJson }}
  log_level: info