apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: {{ .Release.Namespace }}
  labels:
    app: gke-static-node-ip
    component: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-static-node-ip
      component: distributor
  template:
    metadata:
      labels:
        app: gke-static-node-ip
        component: distributor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: NotIn
                  values:
                  {{- range $k, $v := .Values.nodesDesiredIps }}
                  - {{$k}}
                  {{- end }}
      serviceAccountName: distributor
      containers:
      - name: distributor
        image: {{.Values.image.repo}}/{{.Values.image.distributor.image}}:{{.Values.image.distributor.tag}}
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: distributor-config
              key: log_level
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: CHECK_RATE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: distributor-config
              key: check_rate_seconds
        - name: NODES_DATA_RAW
          valueFrom:
            configMapKeyRef:
              name: distributor-config
              key: nodepools_desired_ips
        volumeMounts:
          - name: controller-yaml
            mountPath: /app/controller.yaml
            subPath: daemonset.yaml
        lifecycle:
          preStop:
            exec:
              command: ["python", "-c", "'from distributor import delete_ds_resource; delete_ds_resource()'"]
      volumes:
        - name: controller-yaml
          configMap:
            name: controller-daemonset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixer
  namespace: {{ .Release.Namespace }}
  labels:
    app: gke-static-node-ip
    component: fixer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-static-node-ip
      component: fixer
  template:
    metadata:
      labels:
        app: gke-static-node-ip
        component: fixer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: NotIn
                  values:
                  {{- range $k, $v := .Values.nodesDesiredIps }}
                  - {{$k}}
                  {{- end }}
      serviceAccountName: gke-static-node-ip
      containers:
      - name: fixer
        image: {{.Values.image.repo}}/{{.Values.image.fixer.image}}:{{.Values.image.fixer.tag}}
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: fixer-config
              key: project_id
        - name: NETWORK_TIER
          valueFrom:
            configMapKeyRef:
              name: fixer-config
              key: network_tier
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: fixer-config
              key: log_level