# email of Service Account in GCP with all permissions from README.md
# Don't forget to add IAM binding
# gcpServiceAccount: SA_NAME@PROJECT_ID.iam.gserviceaccount.com

# Use your project ID
# projectId: PROJECT_ID

# Select Network Tier: STANDARD or PREMIUM
networkTier: STANDARD

# NodePool -> IP set config
# If you specify 2 or more IPs, it's assumed that
# the number of Nodes in this nodepool is equal to number of IPs
# you specify
# nodesDesiredIps:
#   demo1:
#     - 123.12.12.12
#     - 133.13.13.13
#   demo2:
#     - 36.123.34.45

image:
  repo: ghcr.io/guga-tm
  fixer:
    image: gkesnip-fixer
    tag: main
  controller:
    image: gkesnip-controller
    tag: main
  distributor:
    image: gkesnip-distributor
    tag: main

distributor:
  checkRateSeconds: 60
  logLevel: info
controller:
  checkRateSeconds: 15
  logLevel: info
fixer:
  logLevel: info